name: 'Wait-For-Other-Pipelines'
description: 'Wait for other pipelines'
branding:
  icon: pause
  color: purple
inputs:
  step-name:  # id of input
    description: 'Step Name'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/wait.sh "${{ inputs.step-name }}"
      shell: bash
